name: Deploy to Github Pages 🚀

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:    
      - main
      - 'releases/**'
env: 
  WEB_DIR: build/WebGL
  
jobs:
  deployPages:
      name: Deploy to Github Pages 🚀 🕸 
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Download artifacts2
         uses: dawidd6/action-download-artifact@v2.24.0
         with:
          workflow: deploy-to-webgl.yml
          workflow_conclusion: success   
          path: build
          
       - name: Test downloads
         run: ls -R
         working-directory: build

       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@4.1.4
         with:
           branch: gh-pages
           folder: build/build-WebGL/WebGL
