name: 3. Test Runner ✨
on: [workflow_call, workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
   
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity-project-with-correct-tests
        unityVersion:
          - 2019.2.11f1
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v3
        with:
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      # Configure test runner
      - name: Run tests
        id: playMode
        uses: ./
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: playmode
          artifactsPath: artifacts/playmode

      # Upload artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test results (play mode)
          path: ${{ steps.playMode.outputs.artifactsPath }}
          retention-days: 14

      # Upload coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Coverage results (play mode)
          path: ${{ steps.playMode.outputs.coveragePath }}
          retention-days: 14


    # testRunnerInEditMode:
    # name: Test edit mode 📝
    # runs-on: ubuntu-latest
    # strategy:
      # fail-fast: false
      # matrix:
        # unityVersion:
          # - 2019.2.11f1
        # projectPath:
          # - unity-project-with-correct-tests
    # steps:
      # ###########################
      # #         Checkout        #
      # ###########################
      # - uses: actions/checkout@v3
        # with:
          # lfs: true

      # ###########################
      # #          Cache          #
      # ###########################
      # - uses: actions/cache@v3
        # with:
          # path: ${{ matrix.projectPath }}/Library
          # key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          # restore-keys: |
            # Library-${{ matrix.projectPath }}-
            # Library-
      # # Configure test runner
      # - name: Run tests
        # id: editMode
        # uses: ./
        # with:
          # projectPath: ${{ matrix.projectPath }}
          # unityVersion: ${{ matrix.unityVersion }}
          # testMode: editmode
          # artifactsPath: artifacts/editmode

      # # Upload artifacts
      # - name: Upload test results
        # uses: actions/upload-artifact@v3
        # with:
          # name: Test results (edit mode)
          # path: ${{ steps.editMode.outputs.artifactsPath }}
          # retention-days: 14

      # # Upload coverage
      # - name: Upload coverage results
        # uses: actions/upload-artifact@v3
        # with:
          # name: Coverage results (edit mode)
          # path: ${{ steps.editMode.outputs.coveragePath }}
          # retention-days: 14